"""Catálogo de doces da Doce Pausa.

Só entram receitas que estudantes conseguem fazer em casa ou na cantina:
nada de macarons, entremets, fondant ou sobremesas que exijam maçarico.

Os preços "de" são de padaria/confeitaria; os preços "por" são de propósito
absurdos, é assim que a isca do phishing funciona.
"""

CATEGORIAS = [
    {"id": "chocolate", "nome": "Brigadeiros e trufas", "emoji": "🍫"},
    {"id": "bolos", "nome": "Bolos e tortas", "emoji": "🍰"},
    {"id": "biscoitos", "nome": "Cookies e biscoitos", "emoji": "🍪"},
    {"id": "copinhos", "nome": "Copinhos e gelados", "emoji": "🍮"},
    {"id": "festa", "nome": "Doces de festa", "emoji": "🍎"},
]

DOCES = [
    # ---- Brigadeiros e trufas ----
    {
        "id": "brigadeiro",
        "nome": "Brigadeiro tradicional",
        "categoria": "chocolate",
        "emoji": "🍫",
        "descricao": "O clássico de chocolate, enrolado no granulado.",
        "preco_original": 3.00,
        "preco": 1.00,
        "tag": "Mais vendido",
    },
    {
        "id": "beijinho",
        "nome": "Beijinho de coco",
        "categoria": "chocolate",
        "emoji": "🥥",
        "descricao": "Leite condensado, coco ralado e um cravinho no topo.",
        "preco_original": 3.00,
        "preco": 1.00,
        "tag": None,
    },
    {
        "id": "brigadeiro-ninho",
        "nome": "Brigadeiro de leite ninho",
        "categoria": "chocolate",
        "emoji": "🥛",
        "descricao": "Branquinho, cremoso e com sabor de leite em pó.",
        "preco_original": 3.50,
        "preco": 1.50,
        "tag": None,
    },
    {
        "id": "cajuzinho",
        "nome": "Cajuzinho",
        "categoria": "chocolate",
        "emoji": "🥜",
        "descricao": "Amendoim moído com chocolate, coberto de açúcar.",
        "preco_original": 3.00,
        "preco": 1.00,
        "tag": None,
    },
    {
        "id": "trufa",
        "nome": "Trufa de chocolate",
        "categoria": "chocolate",
        "emoji": "🍬",
        "descricao": "Recheio de ganache envolvido em chocolate ao leite.",
        "preco_original": 5.00,
        "preco": 1.50,
        "tag": "Novo",
    },
    {
        "id": "palha-italiana",
        "nome": "Palha italiana",
        "categoria": "chocolate",
        "emoji": "🥮",
        "descricao": "Brigadeiro com pedacinhos crocantes de biscoito.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": None,
    },
    # ---- Bolos e tortas ----
    {
        "id": "torta-limao",
        "nome": "Fatia de torta de limão",
        "categoria": "bolos",
        "emoji": "🍋",
        "descricao": "Base crocante, creme de limão e cobertura de merengue.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": "Últimas unidades",
    },
    {
        "id": "bolo-cenoura",
        "nome": "Bolo de cenoura com chocolate",
        "categoria": "bolos",
        "emoji": "🥕",
        "descricao": "Fatia fofinha com aquela cobertura de brigadeiro.",
        "preco_original": 5.00,
        "preco": 1.50,
        "tag": "Mais vendido",
    },
    {
        "id": "bolo-chocolate",
        "nome": "Fatia de bolo de chocolate",
        "categoria": "bolos",
        "emoji": "🎂",
        "descricao": "Massa molhadinha e recheio cremoso de chocolate.",
        "preco_original": 5.50,
        "preco": 2.00,
        "tag": None,
    },
    {
        "id": "torta-morango",
        "nome": "Fatia de torta de morango",
        "categoria": "bolos",
        "emoji": "🍓",
        "descricao": "Creme de leite condensado e morangos fresquinhos.",
        "preco_original": 7.00,
        "preco": 2.50,
        "tag": "Últimas unidades",
    },
    {
        "id": "pao-de-mel",
        "nome": "Pão de mel",
        "categoria": "bolos",
        "emoji": "🍯",
        "descricao": "Massa de mel e especiarias com doce de leite.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": None,
    },
    {
        "id": "cupcake",
        "nome": "Cupcake de baunilha",
        "categoria": "bolos",
        "emoji": "🧁",
        "descricao": "Cobertura de chantilly colorido e confeitos.",
        "preco_original": 7.00,
        "preco": 2.50,
        "tag": "Novo",
    },
    # ---- Cookies e biscoitos ----
    {
        "id": "cookie",
        "nome": "Cookie de gotas de chocolate",
        "categoria": "biscoitos",
        "emoji": "🍪",
        "descricao": "Crocante por fora, macio por dentro.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": "Mais vendido",
    },
    {
        "id": "brownie",
        "nome": "Brownie de chocolate",
        "categoria": "biscoitos",
        "emoji": "🟫",
        "descricao": "Casquinha crocante e miolo bem molhadinho.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": None,
    },
    {
        "id": "casadinho",
        "nome": "Casadinho",
        "categoria": "biscoitos",
        "emoji": "🥠",
        "descricao": "Dois biscoitinhos de maisena com doce de leite no meio.",
        "preco_original": 3.50,
        "preco": 1.20,
        "tag": None,
    },
    {
        "id": "pacoca",
        "nome": "Paçoca rolha",
        "categoria": "biscoitos",
        "emoji": "🌰",
        "descricao": "Amendoim e açúcar, do jeito que a vovó fazia.",
        "preco_original": 2.00,
        "preco": 0.50,
        "tag": None,
    },
    # ---- Copinhos e gelados ----
    {
        "id": "pudim",
        "nome": "Pudim de leite no copinho",
        "categoria": "copinhos",
        "emoji": "🍮",
        "descricao": "Sem furinhos e com muita calda de caramelo.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": None,
    },
    {
        "id": "mousse-maracuja",
        "nome": "Mousse de maracujá",
        "categoria": "copinhos",
        "emoji": "🥣",
        "descricao": "Azedinho na medida, com calda de maracujá.",
        "preco_original": 5.00,
        "preco": 1.50,
        "tag": None,
    },
    {
        "id": "bolo-pote",
        "nome": "Bolo de pote ninho com morango",
        "categoria": "copinhos",
        "emoji": "🍰",
        "descricao": "Camadas de bolo, creme de ninho e morangos.",
        "preco_original": 8.00,
        "preco": 3.00,
        "tag": "Novo",
    },
    {
        "id": "brigadeiro-colher",
        "nome": "Brigadeiro de colher",
        "categoria": "copinhos",
        "emoji": "🥄",
        "descricao": "Aquele de comer com colher, direto do copinho.",
        "preco_original": 5.00,
        "preco": 1.50,
        "tag": None,
    },
    {
        "id": "sacole",
        "nome": "Sacolé de chocolate",
        "categoria": "copinhos",
        "emoji": "🍧",
        "descricao": "Geladinho cremoso para o calor do recreio.",
        "preco_original": 4.00,
        "preco": 1.00,
        "tag": None,
    },
    # ---- Doces de festa ----
    {
        "id": "maca-do-amor",
        "nome": "Maçã do amor",
        "categoria": "festa",
        "emoji": "🍎",
        "descricao": "Maçã coberta com calda vermelhinha e crocante.",
        "preco_original": 6.00,
        "preco": 2.00,
        "tag": "Últimas unidades",
    },
    {
        "id": "pipoca-doce",
        "nome": "Pipoca doce",
        "categoria": "festa",
        "emoji": "🍿",
        "descricao": "Pipoca caramelizada, saquinho cheio.",
        "preco_original": 4.00,
        "preco": 1.50,
        "tag": None,
    },
    {
        "id": "cocada",
        "nome": "Cocada de forno",
        "categoria": "festa",
        "emoji": "🏝️",
        "descricao": "Coco queimadinho por cima e macio por dentro.",
        "preco_original": 3.50,
        "preco": 1.00,
        "tag": None,
    },
    {
        "id": "pe-de-moleque",
        "nome": "Pé de moleque",
        "categoria": "festa",
        "emoji": "🥜",
        "descricao": "Amendoim crocante numa barrinha de rapadura.",
        "preco_original": 4.00,
        "preco": 1.20,
        "tag": None,
    },
]


def _completar(doce):
    """Calcula o desconto para o selo do card."""
    doce["desconto"] = round((1 - doce["preco"] / doce["preco_original"]) * 100)
    return doce


DOCES = [_completar(d) for d in DOCES]
DOCES_POR_ID = {d["id"]: d for d in DOCES}
